Add Trigger Warnings
anirudhb/prox2 pull request #82
Opened 2021-08-24 00:44 UTC by neelr

Fixes #64

2021-08-24 00:52 UTC, anirudhb requested changes
nits, also I think this fork is out of date(?)

2021-08-24 00:52 UTC, anirudhb commented on lib/main.ts
> +  tw_text = ""
```suggestion
  tw_text: string | null = null,
```

2021-08-24 00:52 UTC, anirudhb commented on lib/main.ts
> +        `*${record.id}*: ${tw_text == "" ? record.text : tw_text}`
```suggestion
        `*${record.id}*: ${tw_text ?? record.text}`
```

2021-08-24 00:52 UTC, anirudhb commented on pages/api/interaction_work.ts
> +        });
The record should be fetched first so that the confession view is atomic

2021-08-24 00:52 UTC, anirudhb commented on lib/main.ts
> +        `*${record.id}*: ${tw_text == "" ? record.text : tw_text}`
Add something that indicates it's a TW, like `TW: blah blah, open thread to view confession`

2021-08-24 00:52 UTC, anirudhb commented on pages/api/interaction_work.ts
> +        });
Also, the TW should be added to the DB (update the schema)

2021-08-24 16:00 UTC, neelr commented
> nits, also I think this fork is out of date(?)

I thinkkk its up to date with the master branch, I pulled before working, and the latest commit is there

2021-09-01 15:32 UTC, anirudhb approved these changes
lgtm, need to test this sometime. Do you mind setting up your own prox2 instance to test this and DM me the results on slack?

2021-09-01 15:32 UTC, anirudhb commented on lib/main.ts
> +        ),
Mind moving this to the end so it doesn't break muscle memory

2021-10-01 01:57 UTC, neelr commented
I checked it in #botspam, should work and have all the bugs ironed out

2021-10-01 03:41 UTC, anirudhb commented
Thanks so much for sticking with me on this! Ready to merge :)

2021-10-01 03:41 UTC, merged