Add undo ability for reviewers
anirudhb/prox2 pull request #88
Opened 2023-09-21 06:06 UTC by Merlin04

This PR adds the ability to undo a review decision. It leaves logs in the channel about the decision that was being undone and who undid it to reduce likelihood of abuse. I've also refactored some components (extracted out interaction handlers into separate files and made a single system to pack data into view callback ids), updated some dependencies, and fixed some bugs.

2023-09-21 06:10 UTC, Merlin04 commented
oh, also - you'll need to update the oauth scopes to match what's in the updated manifest

2023-10-03 03:19 UTC, anirudhb requested changes

2023-10-03 03:19 UTC, anirudhb commented on package.json
> +    "dev": "env NODE_OPTIONS=--openssl-legacy-provider next",
Please do not include hacks specific to your machine in the PR

2023-10-03 03:21 UTC, anirudhb commented
Build failed, take a look

2023-10-04 04:19 UTC, anirudhb approved these changes
tested, seems to work!

2023-10-04 04:22 UTC, merged